### ISSUE TITLE
get method error with none recordsets

### ISSUE THREAD

**Issue by qijianjun** [pwwang/pymedoo#5]
If no recordset returned from select method, get method encountered with the following error, maybe it's better to return None.

```
  File "C:\Develop\Python27\lib\site-packages\medoo\base.py", line 95, in get
    return rs.first()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

src:

```python
	def get(self, table, columns = '*', where = None, join = None):
		rs = self.select(table, columns, where, join)
		return rs.first()[0]
```

**Comment by pwwang** [comment]
You may use `try except` to capture the exception, or I am considering raising a new exception based upon the `TypeError`.

**Comment by pwwang** [comment]
Try to `get` from an empty record will now raise `GetFromEmptyRecordError`. 1c34788ebf32912955ae47958fc8c9fabc99aee6
