### ISSUE TITLE
Package branched on pypi

### ISSUE THREAD

**Issue by pwwang** [pwwang/pymedoo#9]
It seems like thats the last vesion on pip see [Release history](https://pypi.org/project/medoo/#history)

_Originally posted by @shkumbinhasani in https://github.com/pwwang/pymedoo/issues/6#issuecomment-799797543_

@shkumbinhasani 
Ah, good catch. I was accidently branched another one on pypi:
https://pypi.org/search/?q=medoo

Will fix it soon. 
For a temporary solution, use 
```
pip install -U pymedoo
```

**Comment by shkumbinhasani** [comment]
Great Stuff! Keep it up

**Comment by pwwang** [comment]
Should be fixed now.
Feel free to reopen or open new issues if you have any other questions.
